<?php
# This file was automatically generated by the MediaWiki 1.39.0-wmf.10
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

###
# Comment out these lines to turn off debugging.  Uncomment to debug.  Keep these lines at the top of this file.

error_reporting( -1 );
ini_set( 'display_errors', 1 );
$wgShowExceptionDetails = true;
$wgDebugToolbar = true;
$wgShowDebug = true;
$wgDevelopmentWarnings = true;
$wgDebugDumpSql = true;
$wgDebugComments = true; 

## Uncomment this to disable output compression
$wgDisableOutputCompression = true;

$wgSitename = "XtremeHebrew";
$wgMetaNamespace = "Xtreme";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL

##
# In order to make short urls to work, you will also need the .htaccess file.  
# An example file is stored in this directory, but you need to change the name
# from "htacess" to "mediawiki-source-code/.htaccess"
# LocalSettings.php will be stored at "mediawiki-source-code/w/LocalSettings.php"
$wgScriptPath = "/w";
$wgArticlePath = "/wiki/$1";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://mygreatwebsite.local";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/resources/assets/greatwebsite-small.jpg",
];
$wgFavicon = "$wgResourceBasePath/resources/assets/greatwebsite-fav.png";

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@🌻.invalid"; // Need if email sending is setup
$wgPasswordSender = "apache@🌻.invalid"; // Need if email sending is setup

$wgEnotifUserTalk = false; 
$wgEnotifWatchlist = false; 
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "127.0.0.1"; // localhost
$wgDBname = "databasename";
$wgDBuser = "user";
$wgDBpassword = "password";

# MySQL specific settings
$wgDBprefix = "mw_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4, DEFAULT COLLATE=utf8mb4_0900_as_ci";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
# $wgSharedTables[] = "actor";

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false; // allow info to be sent back to developers

$wgSecretKey = "e2e73c5fc6b9ff0c47dbeda7571fd5f664f9126b05a30075271e873edacd2870";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "ec95d275d0e7ec18";

#
## Skins
#$wgDefaultSkin = "Metrolook";
$wgDefaultSkin = "Timeless";
$wgFallbackSkin = "vector";

#wfLoadSkin( 'Metrolook' );
#$wgMetrolookDownArrow = false; 
#$wgMetrolookBartile = false; 
#$wgMetrolookFeatures = array( 'collapsiblenav' => array( 'global' => #false, 'user' => false ) );
#wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );

# End of automatically generated settings.
# Add more configuration options below.

include "$IP/LocalSettings/LocalConfiguration.php";
include "$IP/LocalSettings/LocalNamespaces.php";
include "$IP/LocalSettings/LocalExtensions.php";
include "$IP/LocalSettings/LocalPermissions.php";

$wgShowExceptionDetails = true;

